"""se cambia el campo imagen en categorias 

Revision ID: 1f88b23c766b
Revises: c0cbe260ce89
Create Date: 2021-11-21 22:24:12.765344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f88b23c766b'
down_revision = 'c0cbe260ce89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('imagen', sa.String(length=250), nullable=False))
    op.drop_column('productos', 'imagen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('categoria', 'imagen')
    # ### end Alembic commands ###
