"""se agrega el campo categoria_id en la tabla producto 

Revision ID: 88edc350dd10
Revises: af63f0e66111
Create Date: 2021-11-18 00:19:35.775221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88edc350dd10'
down_revision = 'af63f0e66111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'categoria', ['categoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'categoria_id')
    # ### end Alembic commands ###
