"""Initial database

Revision ID: af63f0e66111
Revises: 
Create Date: 2021-11-16 23:00:20.704862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af63f0e66111'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colores', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('descripcion', sa.String(length=256), nullable=False),
    sa.Column('imagen', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talles', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('talle_id', sa.Integer(), nullable=True),
    sa.Column('imagen_name', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['talle_id'], ['talles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_producto')
    op.drop_table('talles')
    op.drop_table('productos')
    op.drop_table('color')
    op.drop_table('categoria')
    op.drop_table('blog_user')
    # ### end Alembic commands ###
