"""se agrega largo al campo url 

Revision ID: c0cbe260ce89
Revises: 88edc350dd10
Create Date: 2021-11-20 04:04:48.847002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0cbe260ce89'
down_revision = '88edc350dd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_user', 'is_active')
    op.drop_constraint('productos_ibfk_1', 'productos', type_='foreignkey')
    op.drop_column('productos', 'categoria_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('productos_ibfk_1', 'productos', 'categoria', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.add_column('blog_user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
